ext {
    projectShortName = "azure-gradle-plugins-common"
    projectName = "Common Lib for Azure Gradle Plugins"
    projectDescription = "A common lib for sharing code among azure gradle plugins"
}

dependencies {
    implementation gradleApi()

    implementation libs.commons.io
    implementation libs.apache.commons.lang3
    implementation libs.google.guava
    implementation libs.slf4j.api
    implementation libs.azure.toolkit.common.lib
    implementation libs.azure.toolkit.appservice.lib
    implementation libs.azure.toolkit.applicationinsights.lib
    testImplementation libs.junit4
    testImplementation libs.mockito.core

    compileOnly libs.project.lombok
    annotationProcessor libs.project.lombok
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourceJar
            artifact javadocJar
            pom {
                name = projectName
                description = projectDescription
                url = "https://github.com/microsoft/azure-gradle-plugins/tree/master/" + projectShortName
                licenses {
                    license {
                        name = "MIT License"
                        url = "https://opensource.org/licenses/MIT"
                        distribution = "repo"
                    }
                }
                developers {
                    developer {
                        id = "andxu"
                        name = "Andy Xu"
                        email = "andxu@microsoft.com"
                    }

                    developer {
                        id = "Flanker32"
                        name = "Hanxiao Liu"
                        email = "hanli@microsoft.com"
                    }
                }
                scm {
                    connection = "scm:git:https://github.com/microsoft/azure-gradle-plugins"
                    developerConnection = "scm:git:git@github.com:microsoft/azure-gradle-plugins"
                    url = "https://github.com/microsoft/azure-gradle-plugins/tree/master/" + projectShortName
                }
            }
        }
    }
}
