/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */
plugins {
    alias(libs.plugins.freefair.aspectj.post.compile.weaving)
}

dependencies {
    implementation libs.commons.io
    implementation libs.apache.commons.exec
    implementation libs.apache.commons.lang3
    implementation libs.reflections
    implementation libs.classindex
    implementation libs.google.gson
    implementation libs.google.guava
    implementation libs.apache.maven.artifact
    implementation libs.fusesource.jansi
    implementation libs.jackson.dataformat.properties

    implementation libs.azure.toolkit.common.lib
    aspect libs.azure.toolkit.common.lib

    implementation libs.azure.toolkit.appservice.lib
    implementation libs.azure.toolkit.applicationinsights.lib

    implementation project(':azure-gradle-plugins-common')

    compileOnly libs.project.lombok
    annotationProcessor libs.project.lombok

    testImplementation libs.junit4
    testImplementation libs.mockito.core
}

jar {
    manifest {
        attributes 'Implementation-Version': project.version
        attributes 'Automatic-Module-Name': 'com.microsoft.azure.azurefunctions'
    }
}

gradlePlugin {
    website = 'https://github.com/microsoft/azure-gradle-plugins/wiki'
    vcsUrl = 'https://github.com/microsoft/azure-gradle-plugins'

    plugins {
        "${project.pluginDisplayName}" {
            id                  = project.pluginId
            displayName         = 'Azure Functions Plugin for Gradle'
            description         = 'Azure Functions Plugin for gradle'
            tags                = ['microsoft', 'azure', 'functions', 'cloud', 'serverless', 'deploy']
            implementationClass = project.pluginImplementationClass
        }
    }
}
