/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */
plugins {
    alias(libs.plugins.freefair.aspectj.post.compile.weaving)
}

dependencies {
    implementation libs.commons.io
    implementation libs.apache.commons.exec
    implementation libs.apache.commons.lang3
    implementation libs.google.gson
    implementation libs.google.guava

    implementation libs.fusesource.jansi
    implementation libs.applicationinsights.core
    implementation libs.apache.maven.artifact
    implementation libs.json.schema.validator
    implementation libs.jackson.dataformat.properties

    implementation libs.azure.toolkit.common.lib
    aspect libs.azure.toolkit.common.lib
    implementation libs.azure.toolkit.appservice.lib
    implementation libs.azure.toolkit.applicationinsights.lib

    compileOnly libs.project.lombok
    annotationProcessor libs.project.lombok

    implementation project(':azure-gradle-plugins-common')

    testImplementation libs.junit4
    testImplementation libs.mockito.core
}

jar {
    manifest {
        attributes 'Implementation-Version': project.version
        attributes 'Automatic-Module-Name': 'com.microsoft.azure.azurewebapp'
    }
}

gradlePlugin {
    website = 'https://github.com/microsoft/azure-gradle-plugins/wiki'
    vcsUrl = 'https://github.com/microsoft/azure-gradle-plugins'

    plugins {
        "${project.pluginDisplayName}" {
            id                  = project.pluginId
            displayName         = 'Azure Webapp Plugin for Gradle'
            description         = 'Azure Webapp Plugin for gradle'
            tags                = ['microsoft', 'azure', 'webapp', 'cloud', 'appservice', 'deploy']
            implementationClass = project.pluginImplementationClass
        }
    }
}
